services:
  - type: web
    name: fastapi-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: MONGO_URL
        value: "mongodb+srv://ilitecode_db_user:LiteCode@1222@cluster0.c90tk5x.mongodb.net/?appName=Cluster0"
      - key: DB_NAME
        value: "Interview-Schedular"


